delete from concept;
insert into concept values (1, 1, 'Jedi', 'Abstracts', 9, 'An ancient religion whose followers defend the galaxy and are beleived to have legendary powers.');
insert into concept values (2, 1, 'The Force', 'Abstracts', 9, 'The name for the energy that ties the universe together. Jedi and Sith can manipulate this energy.');
insert into concept values (3, 1, 'Darth Vader', 'Characters', 1, 'An evil Sith Lord named Anakin Skywalker. Underground leader of the Empire and father to Luke Skywalker and Leia Organa.');
insert into concept values (4, 2, 'Han Solo', 'Characters', 1, 'A human male smuggler who goes on to become a leader of the Rebel Alliance against the empire.');
insert into concept values (5, 2, 'Chewbacca', 'Creatures', 2, 'A Wookie companion and partner of Han Solo who also goes on to become a leader in the Rebel Alliance.');
insert into concept values (6, 2, 'Millennium Falcon', 'Vehicles', 7, 'Han Solos unique and modified space cruiser and cargo ship. Known as the fastest ship in the galaxy.');
insert into concept values (7, 3, 'R2D2', 'Mecha', 8, 'An astromech droid that contains a lot of knowledge valuable to the Rebel Alliance. Built by Anakin Skywalker.');
insert into concept values (8, 3, 'C3P0', 'Mecha', 9, 'A protocol droid that is the companion to R2D2 and help the Rebel Alliance. Also built by anakin Skywalker.');
insert into concept values (9, 4, 'Wookiee', 'Creatures', 2, 'Wookiees are a species of tall, hairy humanoids that are native to the planet Kashyyyk.');
insert into concept values (10, 4, 'Bowcaster', 'Weapons', 4, 'A bowcaster is also known as a laser crossbow. Is a handcrafted projectile weapon commonly used by Wookiees.');
insert into concept values (11, 4, 'Kashyyyk', 'Environments', 3, 'Kashyyyk is a tree-covered forest planet and the homeworld of the Wookiee species.');
insert into concept values (12, 5, 'Tatooine', 'Environments', 3, 'Tatooine is a desert world in the Outer Rim that is inhabited by poor locals who mostly farm moisture for a living.');
insert into concept values (13, 5, 'Star Destroyer', 'Vehicles', 7, 'A medium-sized capital ship used by the Galactic Empire. A heavily armed warship.');
insert into concept values (14, 6, 'Lightsaber', 'Weapons', 4, 'Also referred to as a laser sword. This was a weapon usually used by the Jedi the Sith and other Force-sensitives.');
insert into concept values (15, 6, 'Scanner Pack', 'Accessories', 5, 'Scanner packs are larger portable scanners commonly used to detect technology and lifeforms.');
insert into concept values (16, 7, 'Hyperdrive', 'Accessories', 5, 'A propulsion system that allows a starship to reach lightspeed and travel in the alternate dimension of hyperspace.');